### PR TITLE
Add iPhone X support for screen size

### PR DESCRIPTION
**Pull request by arasu01**
Add iPad support for screen size

### CODE REVIEW

**Comment by nikans** [comment]
Please merge this :P

**Comment by Ekhoo** [comment]
Can you also add the `Device type` ? And then I will make a new release with your PR.

**Comment by arasu01** [comment]
@Ekhoo : I thought of giving that as separated PR. I yet find the details of ``` device type ```

**Comment by Ekhoo** [comment]
Ok perfect ! Thanks a lot !

**Pull request merged**
