### PR TITLE
Adding support for iPhone 12 devices and previously missing ones

### PR DESCRIPTION
**Pull request by ozgur**
Thanks to @felixbuenemann, this PR covers [his changes](https://github.com/Ekhoo/Device/pull/103) as well as new types of iPhone 12 devices that have been recently introduced.

Thus, it fixes the following issues: https://github.com/Ekhoo/Device/pull/90, https://github.com/Ekhoo/Device/issues/94, https://github.com/Ekhoo/Device/issues/101, https://github.com/Ekhoo/Device/issues/105.

### CODE REVIEW

**Comment by EdSancha** [comment]
It seems that the new iPad Air and iPad Pro versions are missing here too, is it better to do it in a new PR? I could help with that.

**Comment by ozgur** [comment]
@EdSancha you can take my and @felixbuenemann 's commits and add a new PR containing them, just like what I've done with his commit.

**Comment by EdSancha** [comment]
Once I downloaded it I realized those devices were also included! Thanks and hopefully @Ekhoo will merge this soon. Thanks a lot for your contribution

**Comment by ozgur** [comment]
@Ekhoo any update on getting this merged?

**Comment by florianpreknya** [comment]
Thanks for your contribution @felixbuenemann! I'm waiting for this merge, too.

**Comment by insubliminal** [comment]
use this pod 'Device' :git => 'https://github.com//ozgur/Device.git'

**Comment by ozgur** [comment]
@Ekhoo any update on getting this merged?

**Comment by teameh** [comment]
@Ekhoo anything we can do to help getting this released?

**Comment by Ekhoo** [comment]
Sorry guys, I'll merge it today

**Comment by teameh** [comment]
Awesome! No worries. Would you be so kind to also release a new version 😊 ?

**Comment by johndpope** [comment]
pod 'Device', :git => 'https://github.com/Ekhoo/Device.git', :commit =>'f2f796b86201cd96271417b99dfd41eb338db395'

**Pull request merged**
