### PR TITLE
added iPad Pro 10.5 and new iPad Pro 12.9 (2017) support

### PR DESCRIPTION
**Pull request by Sweefties**
added iPad Pro 10.5 (7,3 7,4) support
added iPad Pro 12.9 new generation 2017 (7,1 7,2) support

### CODE REVIEW

**Comment by pducks32** [comment]
Hey @Ekhoo can we push this?

**Comment by scottcc** [comment]
👍 This.

**Comment by scottcc** [comment]
FWIW, I can't wait for this small-but-important MR to be added - in particular for the use of DeviceLayout. So, while I'd rather go back to DeviceLayout/Device, there's now a pushed:

* DeviceLayoutSCC : https://github.com/scottcc/DeviceLayout/blob/master/DeviceLayoutSCC.podspec
* DeviceSCC: https://github.com/scottcc/Device/blob/master/DeviceSCC.podspec

Essentially merges #47 and updates DeviceLayout as well.

**Comment by Ekhoo** [comment]
Sorry for the delay, I will release a new version today ! Thank you for your PR :)

**Comment by Ekhoo** [comment]
Here is the new release [v3.0.2](https://github.com/Ekhoo/Device/releases/tag/3.0.2)

**Pull request merged**
