### PR TITLE
Add shorcut isPad, isPhone, isPod

### PR DESCRIPTION
**Pull request by PGLongo**

### CODE REVIEW

**Comment by PGLongo** [comment]
Fix #18

**Comment by Ekhoo** [comment]
Thank you for your PR, but can you handle the Simulator case also ? And can you add thoses example in the Readme in the Device Type section.  Thank you a lot

**Comment by PGLongo** [comment]
Sure.

**Comment by Ekhoo** [comment]
:+1:

**Comment by PGLongo** [comment]
Done!

**Pull request merged**
