### PR TITLE
updated iphone and ipad models, added the '18 products, made compatible with Swift 4.2, updated readme and added some code completion comments

### PR DESCRIPTION
**Pull request by nikans**
also changed unnecessary "static open" for "static public" to keep the checker happy

### CODE REVIEW

**Comment by nikans** [comment]
So, list of fixes:
- added new iphones and ipads, screen sizes and all; added some missed old model names, too
- swift 4.2 Xcode 10 compatibility fixes
- updated readme

**Comment by nikans** [comment]
added useful comments for screen sizes — because it's now a bit hard to navigate all those 6.1 vs 6.5 etc diagonals

**Comment by attheodo** [comment]
@Ekhoo any chance this or #68 or #67 get merged soon?

**Comment by Ekhoo** [comment]
Well done thx 👍

**Comment by Ekhoo** [comment]
I cannot release a new cocoapod version right now because I have an error with the mac target during the pod trunk push and I don't really have the time to fix it :(

**Pull request merged**
