### PR TITLE
Differentiate iPad pro 12.9 and 9.7 inch

### LINKED ISSUE #23: Differentiate iPad pro 12.9inch vs 9.7inch

### PR DESCRIPTION
**Pull request by tbaranes**
Close #23

### CODE REVIEW

**Comment by tbaranes** [comment]
Up, any news about this? It's not a big change 😆

**Comment by tbaranes** [comment]
@Ekhoo Just rebased that PR. Any chance to see this merged?

**Comment by Ekhoo** [comment]
Can you rebase your PR please ? Then I will merge it.

**Comment by tbaranes** [comment]
Done 👍

**Comment by Ekhoo** [comment]
Thank you :) and sorry to be so long.

**Pull request merged**
