### PR TITLE
Carthage support

### LINKED ISSUE #8: Carthage compatibility
Can you add Carthage compatibility?

Thanks

### PR DESCRIPTION
**Pull request by hoppenichu**
As titled. Fixes #8 and #10.

### CODE REVIEW

**Comment by Ekhoo** [comment]
Hello, thank you for your PR, I will test it and if it's ok I will merge it :)

**Comment by Ekhoo** [comment]
Hello, there are some conflitcts with your PR. If you want to fix it you can, otherwise I will merge #12. Tell me what dou you prefer :)

**Comment by hoppenichu** [comment]
Done!

**Comment by Ekhoo** [comment]
Oh great :) Thank you very much :)

**Comment by Ekhoo** [comment]
I merge ! And I will build a new release today

**Comment by hoppenichu** [comment]
:+1:

**Comment by Ekhoo** [comment]
And here is => https://github.com/Ekhoo/Device/releases/tag/0.0.7

**Pull request merged**
