### PR TITLE
Carthage Support

### LINKED ISSUE #10: Carthage build failed
when run carthage update, the carthage complains build error:

*** Skipped building Device due to the error:
Dependency "Device" has no shared framework schemes
If you believe this to be an error, please file an issue with the maintainers at https://github.com/Ekhoo/Device/issues/new

### PR DESCRIPTION
**Pull request by reallyseth**
I added a framework target and shared the scheme. Tested on my forked repo with Carthage and it worked great! This fixes #10 and #8

### CODE REVIEW

**Comment by hoppenichu** [comment]
Hi!
Though I created a same PR (#11) 2 days ago, is there any problem with it?
I just want to know.

Thanks.

**Comment by reallyseth** [comment]
Oh, I hadn't seen it. Sorry about that, my fault! I'm happy to cancel mine. Hopefully the owner merges yours in soon.

**Comment by hoppenichu** [comment]
Never mind👍I'm relieved to hear that.

**Comment by Ekhoo** [comment]
Hello, thank you very much for your PR but it's fixed in #11. I will build a new release today. Thank you :)

**Comment by Ekhoo** [comment]
I close

**Comment by Ekhoo** [comment]
Here is => https://github.com/Ekhoo/Device/releases/tag/0.0.7

**Pull request closed without merging**
